equinor/data-modelling-tool

- api/src/home/workflow/job_handlers/reverse_description/__init__.py
- web/packages/plugins/apps/analysis-platform/src/components/CustomScrim.tsx
- web/packages/plugins/apps/analysis-platform/src/modules/Analysis/AnalysisView.tsx
- web/packages/plugins/apps/analysis-platform/src/modules/Analysis/components/AnalysisCard.tsx
- web/packages/plugins/apps/analysis-platform/src/modules/Analysis/components/AnalysisChooser.tsx
- web/packages/plugins/apps/analysis-platform/src/modules/Analysis/components/AnalysisInfo.tsx
- web/packages/plugins/shared/common/src/components/UiPluginSelector.tsx
- web/packages/plugins/shared/common/src/context/UiPluginContext.tsx
- web/packages/plugins/ui/sima-task/src/EditReverseTask.tsx
- web/packages/plugins/ui/sima-task/src/EditSimaTask.tsx
- web/packages/plugins/ui/yaml-view/src/index.tsx
- Clicking "Run job" opens a modal with uiPLugins for the task that can be eddited. Clicking submit starts a job with the edited task as parameters.
- Yaml-view always fetches the latest document when rendered, to any changes made can be seen without refreshing
User should be able to edit parameters on a per run basis
closes #1031
> edit input before submitting a run

- web/packages/plugins/apps/dmt-app/src/pages/editor/layout-components/DocumentComponent.tsx
- web/packages/plugins/shared/common/src/context/UiPluginContext.tsx
- web/packages/plugins/ui/default-form/src/BlueprintSchema.ts
- web/packages/plugins/ui/default-form/src/index.tsx
- web/packages/plugins/ui/mermaid/src/index.tsx
- web/packages/plugins/ui/mermaid/src/loader.tsx
* Explorer is removed as an input to UI plugins
* Explorer is a dependency that should not be input to UI plugins. It was only used for getting blueprints inside UI plugins, but this can be done by calling the DMSS API directly instead. 
#1043
> Remove explorer as input to UI plugins

- web/packages/plugins/apps/analysis-platform/src/modules/Analysis/AnalysisView.tsx
- web/packages/plugins/apps/analysis-platform/src/modules/Analysis/components/AnalysisCard.tsx
- web/packages/plugins/apps/analysis-platform/src/modules/Analysis/components/AnalysisInfo.tsx
- web/packages/plugins/apps/analysis-platform/src/modules/Analysis/components/AnalysisJobTable.tsx
Show runned jobs in table instead of hard coded data. 
Still missing duration. To be able to set the duration the end time of the runned job needs to be set.
> show jobs in table

- api/src/home/DMT/data/demoDSAlias/DMT-demo/Plugins/Form/FormBlueprint.json
- api/src/home/DMT/data/demoDSAlias/DMT-demo/Plugins/Form/FormExample.json
- api/src/home/DMT/data/demoDSAlias/DMT-demo/Plugins/Form/Nested.json
- api/src/home/DMT/data/demoDSAlias/DMT-demo/Plugins/Form/SingeField.json
- api/src/home/DMT/data/demoDSAlias/DMT-demo/Plugins/Form/SingleFieldExample.json
- api/src/home/analysis-platform/data/AnalysisPlatformDS/Blueprints/Analysis.json
- web/packages/plugins/ui/form/README.md
- web/packages/plugins/ui/form/src/Form.tsx
- web/packages/plugins/ui/form/src/fields/ArrayField.tsx
- web/packages/plugins/ui/form/src/fields/AttributeField.tsx
- web/packages/plugins/ui/form/src/fields/BooleanField.test.tsx
- web/packages/plugins/ui/form/src/fields/BooleanField.tsx
- web/packages/plugins/ui/form/src/fields/NumberField.test.tsx
- web/packages/plugins/ui/form/src/fields/NumberField.tsx
- web/packages/plugins/ui/form/src/fields/ObjectField.test.tsx
- web/packages/plugins/ui/form/src/fields/ObjectField.tsx
- web/packages/plugins/ui/form/src/fields/StringField.test.tsx
- web/packages/plugins/ui/form/src/fields/StringField.tsx
- web/packages/plugins/ui/form/src/index.tsx
- web/packages/plugins/ui/form/src/types.tsx
- web/packages/plugins/ui/form/src/widgets/TextWidget/TextWidget.tsx
* It should be visible to the users what attributes are optional or not
* It should not be possible to submit form before all non-optional attributes have values
Part of #1072
> Add support for optional in form UI plugin

- api/src/services/job_handler_interface.py
- web/packages/plugins/ui/job/src/Job.tsx
bugfix: the python conversion to isoformat was not as expected.
This caused the job entity in the mongodb to have wrong dateformat for "started"
instead of having the ISO format "2022-04-08T11:23:18.686Z",
the string was stored in local time without the Z: "2022-04-08T13:23:18.686"
the start time in the job runs table was wrong
closes #1083
> update date stored in job handler

- web/packages/plugins/ui/task/src/EditTask.tsx
Added or-argument as input for formData, so truncatepathstring works.
To be able to get the edit plugin for analysis with no data.
> Bugfix: the edit plugin crashed for new analysis

- sre-wrapper/Dockerfile
- Ensures apt packages are up to date in the container image as we're relying on a third-party (SINTEF-managed) container image (`dmtregistry.azurecr.io/sima-runtime`)
- To ensure packages are up to date;
- To minimize the exposure to vulnerabilities in outdated/old packages
> Run apt upgrades on sre-wrapper image

- web/packages/plugins/apps/analysis-platform/src/modules/Analysis/components/AnalysisJobTable.tsx
Changed the url-path for the result in the jobTable to show the result. 
If the result don't exist it will show "None"
> result in jobTable now points to the result

- api/src/services/dmss.py
Job API will skip creating a new PAT if one was posted with the request
Needed so that tools using PAT can start jobs
> Job API will skip creating a new PAT if one was posted with the request

- api/src/home/analysis-platform/data/WorkflowDS/Blueprints/Task.json
- api/src/home/appMooring/data/app_mooring_db/simpos/mooringSRS/MooringSRS.json
- web/packages/plugins/apps/analysis-platform/src/App.tsx
- web/packages/plugins/apps/analysis-platform/src/components/Layout/Header.tsx
- web/packages/plugins/apps/analysis-platform/src/modules/Analysis/AnalysisView.tsx
- web/packages/plugins/apps/analysis-platform/src/utils/auth.tsx
- web/packages/plugins/shared/common/src/components/UiPluginSelector.tsx
- web/packages/plugins/ui/task/src/SIMAInputOnly.tsx
- web/packages/plugins/ui/task/src/index.tsx
- Adds a Task plugin for operator-experts that only displays the SRSConfig
- New feature: Impersonate. dmss-admin gets the option to impersonate an other role
closes #1194
> expert operator task view plugin. Impersonate feature

- api/src/home/analysis-platform/data/WorkflowDS/Blueprints/jobHandlers/JobHandler.json
- web/packages/plugins/apps/analysis-platform/src/modules/Analysis/components/AnalysisCard.tsx
- web/packages/plugins/shared/common/src/components/Pickers/JobHandlerPicker.tsx
- web/packages/plugins/ui/job-handlers/src/EditContainer.tsx
- web/packages/plugins/ui/task/src/EditTask.tsx
* do not use default values for dropdown selector. Force user to select a value. 
* If a value is stored on the task entity, this will be set to the value in the dropdown selector. 
* 
Values in dropdown selectors for "job runner" and "container image" displays a value, but the internal state is empty. This resulted in no values being updated in the entity when pressing save. 
no value selected (no runner stored in the task entity)
after selecting "container" as runner, press save, and reload page: value is automatically selected in the dropdown menu
#1208
> upate logic for dropdown selectors

- api/src/home/analysis-platform/data/WorkflowDS/Blueprints/Job.json
- api/src/home/analysis-platform/job_handlers/local_container/__init__.py
- api/src/services/job_service.py
- web/packages/plugins/apps/analysis-platform/src/Types.ts
- web/packages/plugins/apps/analysis-platform/src/modules/Analysis/components/AnalysisCard.tsx
- web/packages/plugins/apps/analysis-platform/src/modules/Analysis/components/AnalysisJobTable.tsx
- web/packages/plugins/apps/analysis-platform/src/modules/View.tsx
- web/packages/plugins/shared/common/src/components/NewEntityButton.tsx
- web/packages/plugins/shared/common/src/components/Pickers/EntityPickerButton.tsx
- web/packages/plugins/shared/common/src/components/UiPluginSelector.tsx
- web/packages/plugins/shared/common/src/hooks/useDocument.tsx
- web/packages/plugins/ui/job-handlers/src/EditContainer.tsx
- web/packages/plugins/ui/job/src/JobControl.tsx
- web/packages/plugins/ui/job/src/JobEdit.tsx
- web/packages/plugins/ui/job/src/index.tsx
- web/packages/plugins/ui/job/src/types.ts
- web/packages/plugins/ui/sima-application-input/src/EditSimaApplicationInput.tsx
- Rework of how users create, edit and start jobs
- "Run analysis" button now only append jobs to the analysis jobs list
- A new plugin "EditJob" that can be used to edit the job before starting it.
- Renamed "Job" plugin to "JobControl", and added "Start job" button
closes #1211
> Start and edit jobs refactor

- web/packages/plugins/apps/analysis-platform/src/modules/Analysis/components/AnalysisInfo.tsx
- web/packages/plugins/apps/dmt-app/src/components/context-menu/ContextMenu.tsx
Minor UI styling
* disable edit button for Analysis - the edit does not work and I don't think DMSS support changing an entity's name now
* More consistent style for popups from DMT context menu
> UI styling

- web/packages/plugins/shared/common/src/components/Header.tsx
- web/packages/plugins/shared/common/src/utils/appRoles.tsx
- web/packages/plugins/ui/analysis/src/components/AnalysisCard.tsx
- web/packages/plugins/ui/analysis/src/components/AnalysisJobTable.tsx
- Adds an additional role to the 'impersonate role' selector; `inspector`
- Uses the `InspectorView.tsx` view for users with the `inspector` role
- Defines all roles in single file; `appRoles.tsx`
- `APP_ROLES`: All possible roles in the app
- `EXPERT_ROLES`: All `expert` roles
- `OPERATOR_ROLES`: All `expert` roles, as well as the role `operator`
- Adds a function, `hasOperatorRole()`, to `appRoles.tsx`
- Hides the "controls" (run, delete) in `AnalysisJobTable.tsx` for non-operators (inspector)
- Links directly to a result, rather than a job, for non-operators (inspector)
- Hides the "New job" action for non-operators
- To enable a simplified view for the `inspector` role
- Resolves #1256
> Inspector view

- web/packages/plugins/shared/common/src/components/Header.tsx
- web/packages/plugins/shared/common/src/utils/appRoles.tsx
- web/packages/plugins/ui/analysis/src/OperatorView.tsx
- Improves `appRoles.tsx` definitions to avoid duplicate entries
- Hides "default task edit" for non-domain roles (i.e. displayed only for domain-experts and domain-developers)
- Adds a role check util for "domain" users
- Resolves #1266
> Operator analysis view improvements

- web/packages/plugins/ui/blueprint/src/EditBlueprint.tsx
* Attributes not shown bug
Fixes this problem, that the list of blueprint attributes are not shown:
> fix: correctly show list of blueprint attributes

- web/packages/plugins/shared/common/src/domain/Tree.tsx
Initialize the tree correctly - added filter such that only folders in a root package are added to initial tree, instead of all content inside root package. (This caused TreeNode children of type system/SIMOS/Blueprint to be initialized with wrong values)
closes #1263
> set correct type when initializing tree

- web/packages/plugins/ui/analysis/src/components/AnalysisJobTable.tsx
disable delete run button to emphasize that the functionality is not implemented
closes #1277
> disable delete run button

- web/packages/plugins/shared/common/src/components/NewEntityButton.tsx
- web/packages/plugins/shared/common/src/components/Pickers/BlueprintPicker.tsx
- web/packages/plugins/shared/common/src/components/Pickers/DestinationPicker.tsx
- web/packages/plugins/ui/task/src/EditTask.tsx
* add an entity destination input to EditTask. This selection is used in the NewEntityButton.tsx.
* If a entity destination and/or blueprint is selected in EditTask, then the input fields for entity destination and blueprint are hidden in the "new entity button popup"
* Change order of input fields in NewEntityButton.tsx, such that the order is consistent with EditTask.tsx
* minor improvements: fix tooltip for blueprint selector and check type when copying existing entity in NewEntityButton.tsx
closes #1271
> add DestinationPicker to EditTask.tsx, and update NewEntityButton.tsx functionality

- web/packages/plugins/shared/common/src/components/Header.tsx
Adds missing icons needed by shared/common, but contributed by other plugins
> Add missing icons in shared/common

- api/src/home/analysis-platform/data/AnalysisPlatformDS/Blueprints/SIMAApplicationInput.json
- api/src/home/analysis-platform/data/AnalysisPlatformDS/Data/sima_test/ULS_Intact.json
- docker-compose.override.yml
- web/packages/plugins/shared/common/src/components/Pickers/DestinationPicker.tsx
- web/packages/plugins/shared/common/src/components/Pickers/EntityPickerButton.tsx
- web/packages/plugins/shared/common/src/components/TreeView.tsx
- web/packages/plugins/shared/common/src/context/FileSystemTreeContext.tsx
- web/packages/plugins/shared/common/src/domain/Tree.tsx
- web/packages/plugins/ui/sima-application-input/src/EditSimaApplicationInput.tsx
- web/packages/plugins/ui/sima-application-input/src/components.tsx
- A new method to init a Tree, "initFromFolder"
- DestinationPicker and EntitySelector now takes a "scope" param and will use the new Tree init method if provided
- Blueprint and plugin updated for SIMAApplicationInput, providing a "presetInputFolder"
- Some simpler views should not be able to see the whole tree structure on some operations
closes #1306
> feat: create Tree from folder. 

- web/packages/plugins/apps/dmt-app/src/components/context-menu/ContextMenu.tsx
- web/packages/plugins/shared/common/src/domain/Tree.tsx
- web/packages/plugins/ui/job-handlers/src/EditContainer.tsx
- web/packages/plugins/ui/sima-application-input/src/EditSimaApplicationInput.tsx
- web/packages/plugins/ui/task/src/EditTask.tsx
* add indicator for unsaved changes
* Add a function to TreeNode to update content of a datasource node - required to be able to display newly created root 
packages at once
* change order of workflow and workflow task input fields 
closes #1302 
closes #1304 
closes #1301
> Minor fixes

- api/src/services/job_service.py
- web/packages/plugins/ui/analysis/src/components/AnalysisCard.tsx
- Changes the `CardWrapper` styled component's `grid-template-columns` to `1` (a single column) with `auto`, rather than `2` with a hard-coded size (`320px`) to ensure that all children are contained in the wrapper.
The `AnalysisCard` component's `Card.Actions` are overflowing (with the exception of Inspectors and Operators, due to fewer buttons being displayed).
Current:
Fixed by this PR:
- Resolves #1334
> Fix overflowing actions in the `AnalysisCard` component

- api/src/services/job_service.py
- web/packages/plugins/apps/analysis-platform/src/components/Design/Colors.ts
- web/packages/plugins/apps/analysis-platform/src/components/Layout/Content.tsx
- web/packages/plugins/shared/common/src/components/UiPluginSelector.tsx
- Adds an `<a href={absoluteDottedId}/>` to each part of the `<DocumentPath />` (breadcrumb) to allow for navigation by clicking the respective parts of the breadcrumb
- Adds a clickable breadcrumb above the page content (below the header), visible when viewing any document
- Some minor fixes to `job_service.py` due to complaints from the pre-commit pipeline (unused imports, line length)
**Dashboard** (no breadcrumb, as no document is in view)
**Analysis view**
**Job view**
**Application input view**
- To facilitate easier navigation when viewing analyses in the Analysis Platform
- To support clickable breadcrumbs in the existing `<DocumentPath />` component
- Resolves #1148 
- Relates to #1201
> Analysis navigation and clickable breadcrumbs

- api/src/features/jobs/jobs.py
- api/src/features/jobs/use_cases/get_result_job.py
- api/src/features/jobs/use_cases/start_job.py
- api/src/features/jobs/use_cases/status_job.py
- api/src/home/analysis-platform/data/WorkflowDS/Blueprints/Job.json
- api/src/home/analysis-platform/job_handlers/local_container/__init__.py
- api/src/init.sh
- api/src/services/job_handler_interface.py
- api/src/services/job_service.py
- web/packages/home/src/App.js
- web/packages/plugins/shared/common/src/services/JobApi.ts
- web/packages/plugins/shared/common/src/types.ts
- web/packages/plugins/ui/analysis/src/InspectorView.tsx
- web/packages/plugins/ui/analysis/src/OperatorView.tsx
- web/packages/plugins/ui/analysis/src/components/AnalysisJobTable.tsx
- web/packages/plugins/ui/job/src/JobControl.tsx
- JobService now works with UID for started jobs
- Enable delete button on "AnalysisJobTable"
- Should be possible to delete jobs
closes #1313
> feat: job_service now works with uid's. This makes jobs deletable

- api/src/app.py
- web/packages/dmt-core/src/services/api/configs/gen-dmt/api/dmtapi.ts
- web/packages/dmt-core/src/services/api/configs/gen-dmt/api/jobs-api.ts
add security dependecy to the dmt fastapi for job API, to update the openapi schema. 
There was a bug where the requests to job api from dmt web did not include the access token. This caused an auth error in the job api, since the job api use the dmss python package.   
This solution feels a bit hacky, so I am very open to other suggestions for how to fix this. 
I could not find any other way to simple way to solve this.
auth error when using the job api
closes #1385
> fix DMSS authentication bug

- web/packages/plugins/analysis-platform/src/modules/Analysis/components/AnalysisJobTable.tsx
bugfix: do not show "invalid date" in the job table. use the job object directly without the local started state.
bugfix
closes #1376
> fix invalid date bug
