.github/workflows/on-master-push.yaml, .github/workflows/on-tag.yaml, .github/workflows/publish.yaml, .github/workflows/tests.yaml, IaC/README.md, IaC/main.bicep, api/src/utils/create_application_utils.py, docker-compose.ci.yml, docker-compose.yml, radixconfig.yaml
Adds a bicep file to define our infrastructure as code
- Create Azure resources
closes #1056
=> define infrastructure in bicep (IaC)

web/packages/plugins/shared/common/src/components/AccessControlList.tsx, web/packages/plugins/shared/common/src/services/api/DmssAPI.ts
use url instead of generated DMSS API. For some unknown reason the request from generated DMSS API fails. 
bugfix
closes #1047
=> fix acl save error

web/Dockerfile
=> Fix working dir for deployment

web/packages/home/package.json
* It is possible to build with typescript errors
* To be able to build and compile again
=> Ignore typescript errors

api/src/home/workflow/job_handlers/local_container/__init__.py, sre-wrapper/docker-compose.yaml, sre-wrapper/init.sh, sre-wrapper/job_wrapper.py
allow space in container input string, instead of using the "space to %20" conversion"
closes #1084
=> allow space in input string to container

web/package.json, web/packages/plugins/apps/analysis-platform/package.json, web/packages/plugins/ui/default-form/package.json, web/yarn.lock
Upgrade more pacakges to fix dependabot issues
=> updage object-path

api/src/home/analysis-platform/data/AnalysisPlatformDS/Blueprints/SIMAApplicationInput.json
small bug in SimaApplicationInput blueprint
=> fixed curly brackets in SimaApplicationInput blueprint

.github/pull_request_template.md
* Remove checklist from pull request template
* Nobody is using the checklist, no need to have it
=> Remove checklist from pull request template

api/src/home/analysis-platform/data/AnalysisPlatformDS/Data/ApplicationInputs/exampleAppInput.json, api/src/home/analysis-platform/data/WorkflowDS/Blueprints/Task.json, web/packages/plugins/shared/common/src/components/Pickers/EntityPickerButton.tsx
Removed some required attributes from task.
Added fetch function to EntityPickerButton.
Changed exampleAnalysis, so it wont be recursive. 
This PR needs to be merged before https://github.com/equinor/data-modelling-storage-service/pull/200.
=> Edit the task blueprint to be able to save changes

web/packages/plugins/shared/common/src/components/NewEntityButton.tsx, web/packages/plugins/shared/common/src/components/Pickers/DestinationPicker.tsx
Change the placeholder for DestinationPicker.
Change the label for the "new" button on input entity.
=> changed label and placeholder for the "new" button for the input entity

web/packages/plugins/apps/analysis-platform/src/modules/Analysis/components/AnalysisTable.tsx, web/packages/plugins/shared/common/src/components/Pickers/EntityPickerDropdown.tsx, web/packages/plugins/shared/common/src/components/Pickers/JobHandlerPicker.tsx, web/packages/plugins/shared/common/src/hooks/useDocument.tsx, web/packages/plugins/shared/common/src/hooks/useSearch.tsx
Adds generics to public API
Helps with type safety in downstream libs
=> Add generics to public API

web/packages/plugins/shared/common/src/hooks/useDocument.tsx, web/packages/plugins/ui/job-handlers/src/EditContainer.tsx, web/packages/plugins/ui/sima-application-input/src/EditSimaApplicationInput.tsx, web/packages/plugins/ui/tabs/src/TabsContainer.tsx, web/packages/plugins/ui/task/src/EditTask.tsx
Removed common submit/ok/reset button on tabs container. This button(s) have been added inside each of the UIPlugins.
=> Removed common submit button tabs

.github/workflows/template-new-analysis-run.yaml, api/src/home/analysis-platform/job_handlers/azure_container_instances/__init__.py, radixconfig.yaml, scripts/upload-config-run-job.sh
=> wrong dmss url

radixconfig.yaml
=> Fix incorrect env var name for ca cert

.github/workflows/tests.yaml, .pre-commit-config.yaml, api/Dockerfile, api/poetry.lock, api/pyproject.toml, api/src/home/analysis-platform/job_handlers/azure_container_instances/__init__.py, docker-compose.override.yml, docker-compose.yml
- Have Azure Container Instance job handler return correct status codes
- Bump project python version (I really needed a match pattern case)
closes #1216
=> bump python version. fix status codes from Azure job handler

web/package.json, web/yarn.lock
upgrade web packages
fix security issues detected by dependabot
=> dependabot security upgrades

api/src/home/DMT/data/DMT-internals/DMT/ui-plugins/form/FormInput.json, api/src/home/DMT/data/DMT-internals/DMT/ui-plugins/form/fields/ArrayField.json, api/src/home/DMT/data/DMT-internals/DMT/ui-plugins/form/fields/StringField.json, api/src/home/DMT/data/demoDSAlias/DMT-demo/Plugins/Form/Nested.json, api/src/home/DMT/data/demoDSAlias/DMT-demo/Plugins/Form/SingeField.json, api/src/home/analysis-platform/data/AnalysisPlatformDS/Data/Analysis/exampleAnalysis.json, api/src/home/analysis-platform/job_handlers/azure_container_instances/__init__.py, api/src/home/analysis-platform/job_handlers/local_container/__init__.py, web/packages/plugins/apps/dmt-app/src/components/context-menu/ContextMenu.tsx, web/packages/plugins/shared/common/src/components/TreeView.tsx, web/packages/plugins/shared/common/src/components/UploadFileButton.tsx, web/packages/plugins/ui/blueprint/src/index.tsx, web/packages/plugins/ui/form/src/index.tsx, web/packages/plugins/ui/job-handlers/src/EditContainer.tsx, web/packages/plugins/ui/sima-application-input/src/EditSimaApplicationInput.tsx
- Fix a bug that caused EditBlueprint plugin not to render
- Added loading icon on expanding treeNodes in TreeView
-  Added loading icon on EditContainerRunner save button
- Added loading icon on EditSimaInput save button
- Fix a bug causing "append entity to list" in TreeView context menu to fail
- Fixed a bug causing "UplaodFIle" error message not to be cleared when form state changes
=> many minor bug fixes

api/src/home/analysis-platform/data/WorkflowDS/Blueprints/Job.json, api/src/home/appMooring/data/app_mooring_db/simpos/mooringSRS/MooringSRS.json, web/packages/plugins/shared/common/src/components/Pickers/EntityPickerButton.tsx, web/packages/plugins/shared/common/src/utils/truncatePathString.ts, web/packages/plugins/ui/job/src/JobEditAdvanced.tsx, web/packages/plugins/ui/job/src/index.tsx
- New plugin that simplifies jobEdit (edit simaAppInput.input directly)
- Keep old plugin as "jobEditAdvanced"
closes #1234
=> simplify jobEdit

web/packages/plugins/apps/dmt-app/src/pages/SearchPage.tsx
Some bugs on the search page
NOTE: Requires DMSS fix https://github.com/equinor/data-modelling-storage-service/pull/218
=> bug fixes for search page. Now support multiple data sources

web/packages/plugins/ui/task/src/EditTask.tsx
=> loading symbol on save

web/packages/plugins/shared/common/src/services/JobApi.ts
=> Add result to job api

web/packages/plugins/shared/common/src/components/NewEntityButton.tsx
loading icon on create
closes #1253
=> add loading to create new entity button

web/packages/plugins/ui/job-handlers/src/EditContainer.tsx
delete id to make comparison work correctly
closes #1260
=> fix comparison bug in editContainer

web/packages/plugins/shared/common/src/components/Loading.tsx, web/packages/plugins/ui/simpos-ui/src/sima/model/views/FirstOrderMotionTransferFunction.tsx, web/packages/plugins/ui/simpos-ui/src/sima/model/views/QuadCurrentCoeffPlot.tsx, web/packages/plugins/ui/simpos-ui/src/sima/model/views/SIMOBody.tsx, web/packages/plugins/ui/simpos-ui/src/simpos/srs/forms/SRSSceSimulationForm.tsx
more consistent loading functionality
closes #1275
=> fix loading component

web/packages/plugins/apps/analysis-platform/src/modules/Analysis/components/CreateAnalysisForm.tsx
make input field expandable
closes #1273
=> make description input field expandable

web/packages/plugins/ui/analysis/src/components/AnalysisJobTable.tsx
* display correct date after clicking the run button in the job runs list, instead of Invalid date
* improve ui
closes #1284
=> fix invalid date in job runs list

web/packages/plugins/apps/dmt-app/src/pages/editor/Editor.tsx
bugfix: let user be able to re-open a tab if all tabs have been closed
bug
closes #1288
=> bugfix: be able to open new tab if every tab has been closed

api/src/home/DMT/data_sources/Demo.json
Update attributes for azure blob storage. Requires https://github.com/equinor/data-modelling-storage-service/pull/231 to be merged first.
Cannot load DemoDS
=> update azure blob storage attributes

.github/workflows/on-tag.yaml
use correct tag as input to CI workflow
CI fails when triggered by tagging
=> fix tag ref

web/packages/plugins/apps/analysis-platform/package.json, web/packages/plugins/shared/common/package.json, web/packages/plugins/ui/blueprint/package.json, web/packages/plugins/ui/job-handlers/package.json, web/packages/plugins/ui/sima-application-input/package.json, web/packages/plugins/ui/tabs/package.json, web/packages/plugins/ui/task/package.json, web/yarn.lock
upgrade EDS packages
closes #1307 and closes #1310
=> upgrade eds

api/src/app.py, api/src/config.py, api/src/features/system/use_cases/set_application_settings_use_case.py, web/packages/dmt-core/src/types.ts
consistent naming in the dmt settings object
clean up code
closes #1354
=> consistent naming for dmt settings

web/packages/dmt-core/src/components/Header.tsx, web/packages/dmt-core/src/utils/variables.tsx
Set the user info dialog to a fixed size. 
Adjusted the size of the pickers dialog.
=> adjusted the size of the dialog

api/Dockerfile, api/src/init.sh, api/src/repository/file/__init__.py, api/src/utils/create_application_utils.py, docker-compose.override.yml, docker-compose.yml, docs/user-manual.adoc, scripts/reset-db.sh
- Installs python packages in a venv in the container
- Fixes a build problem caused by conflicting packages when project dependencies were installed globally
=> fix: use venv in container

api/src/init.sh
remove factory settings from gunicorn, seems like this is not a valid setting 
api fails on radix
closes #1399
=> fix: try to remove --factory setting in gunicorn

web/packages/dmt-core/src/hooks/useDocument.test.tsx, web/packages/dmt-core/src/hooks/useDocument.tsx, web/packages/dmt-core/src/utils/test-utils-dmt-core.tsx
Added a new test-file to test useDocument Hook and a new utils-test file.
Missing test on UpdateDocument function.
To test useDocument hook. 
Closes #1366.
=> test: useDocument hook
